namespace Manager.Web.Domain;

/// <summary>
/// A domain wrapper for a paginated data set
/// </summary>
/// <typeparam name="T"></typeparam>
public sealed class ManagedPaginatedResponse<T>
{
    /// <summary>
    /// Items found in the paginated response
    /// </summary>
    public T[] Items { get; }

    /// <summary>
    /// Whether the paginated set has more items to return
    /// </summary>
    public bool HasMore { get; }

    /// <summary>
    /// Errors generated by the Server
    /// </summary>
    public ManagedError[] Errors { get; }

    public ManagedPaginatedResponse(T[]? items = null, bool hasMore = false, ManagedError[]? errors = null)
    {
        Items = items ?? Array.Empty<T>();
        HasMore = hasMore;
        Errors = errors ?? Array.Empty<ManagedError>();
    }
}
