name: Build and Deploy Manager.Web app to Azure Web App

on:
  pull_request:
    branches:
      - '*'

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: dotnet build
        run: |
          dotnet restore
          dotnet build --configuration Release